### ISSUE TITLE
Missing time zone for network: Apple Music.

### ISSUE THREAD

**Issue by MaDTaZ** [Sick-Rage/Sick-Rage#4046]
TORNADO :: [d8c2613] Missing time zone for network: Apple Music. Check valid network is set in indexer (theTVDB) before filing issue.

This was when Carpool Karoke was added to sickrage

**Comment by OmgImAlexis** [comment]
Seems the show is listing the incorrect network since CBS is the actual network not Apple music.

https://www.thetvdb.com/?id=327394&tab=series

**Comment by bobbysteel** [comment]
Delete and re-add from SickRage. Seems to be an error in thetvdb data somewhere assigning it to Apple Music which appears fixed.

**Comment by JayTurnr** [comment]
Surely hitting 'Force Full-Update' on the show would be a better move?

**Comment by cbetta** [comment]
@OmgImAlexis this isn't an error that appears for the original CBS series, but for the new 2017 Apple Music series: https://www.thetvdb.com/?tab=series&id=332954
