### ISSUE TITLE
[APP SUBMITTED]: TORNADO :: [4b69468] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by MotleyC** [Sick-Rage/Sick-Rage#4257]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
TORNADO :: [4b69468] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by heula** [comment]
Same error for me since a day or 2 now.

**Comment by HPMSGEN8** [comment]
### INFO
Python Version: **2.7.14 (default, Jan 15 2018, 19:15:25) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [4b69468] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17074**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
Thread-86 :: [4b69468] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HPMSGEN8** [comment]
Getting the same error after the new update

**Comment by LeeThompson** [comment]
It should just default to GMT perhaps with a warning if it's a traditional broadcast network (streaming only it's not even really an applicable concept anymore.)

**Comment by heula** [comment]
Same error for me since a few days.

**Comment by quickdry** [comment]
AFAIK the fix needs to be made to file: https://sickrage.github.io/sb_network_timezones/network_timezones.txt

It isn't a file on the machine, sickrage periodically reaches out over the web to read that file and update it's list of networks. "Paramount Network" isn't in the file/page so it can't assign it. I'm guessing we all have Lip Sync Battle or something from the new network that used to be Spike.

**Comment by statik1983** [comment]
SO IS SOMEONE GOING TO FIX THIS ISSUE THAT WE ALL SEEM TO BE HAVING?!  I can't add any new shows that use theTVDB

**Comment by hairyhippy** [comment]
What was the fix here as I am getting:
2021-07-30 09:32:36 Missing time zone for network: HBO Europe. Check valid network is set in indexer (theTVDB) before filing issue.
