### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [61a763d] Missing time zone for network: Sky1. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by captaincrunch59** [Sick-Rage/Sick-Rage#5005]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:46:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: None
Branch: **master**
Commit: Sick-Rage/Sick-Rage@61a763d303f7337709e03a76b01d9592e2dce14d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [61a763d] Missing time zone for network: Sky1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Diabolino** [comment]
### INFO
Python Version: **2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.9.0-6-amd64-x86_64-with-debian-9.5**
Locale: UTF-8
Branch: **master**
Commit: Sick-Rage/Sick-Rage@61a763d303f7337709e03a76b01d9592e2dce14d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [61a763d] Missing time zone for network: Sky1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Diabolino** [comment]
### INFO
Python Version: **2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.9.0-6-amd64-x86_64-with-debian-9.5**
Locale: UTF-8
Branch: **master**
Commit: Sick-Rage/Sick-Rage@61a763d303f7337709e03a76b01d9592e2dce14d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [61a763d] Missing time zone for network: Sky1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
